/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        oat: {
          50: "#FAF6F2",
          100: "#F5EFEB",
          200: "#EDE6E0",
          300: "#DDD2C7",
          400: "#C5B4A4",
          500: "#A8927D",
          600: "#8A735E",
          700: "#6A5645",
          800: "#463729",
          900: "#2A2018",
          950: "#18110B",
        },
        primary: {
          50: "#F4F1F6",
          100: "#E8E4ED",
          200: "#D2C9DA",
          300: "#B6A8C2",
          400: "#9686A4",
          500: "#7A6A8A",
          600: "#6C5B7B",
          700: "#5A4A68",
          800: "#4F3F5C",
          900: "#3E3148",
          950: "#231C2A",
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          disabled: "var(--color-primary-disabled)",
        },
        secondary: {
          50: "#FEF3EB",
          100: "#FCE0CC",
          200: "#FAC196",
          300: "#F89D60",
          400: "#F57F39",
          500: "#F3722C",
          600: "#D85A1A",
          700: "#B14315",
          800: "#883014",
          900: "#6B2611",
          950: "#3D1208",
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
          hover: "var(--color-secondary-hover)",
          active: "var(--color-secondary-active)",
          disabled: "var(--color-secondary-disabled)",
        },
        accent: {
          50: "#F4FAE3",
          100: "#E5F4C0",
          200: "#D2EE96",
          300: "#BCE368",
          400: "#A5D448",
          500: "#9BCB3C",
          600: "#7AAD2B",
          700: "#5E8821",
          800: "#4A6A1A",
          900: "#385014",
          950: "#1F2D08",
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
          hover: "var(--color-accent-hover)",
          active: "var(--color-accent-active)",
          disabled: "var(--color-accent-disabled)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          muted: "var(--color-surface-muted)",
          elevated: "var(--color-surface-elevated)",
          sunken: "var(--color-surface-sunken)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        disabled: {
          DEFAULT: "var(--color-disabled)",
          foreground: "var(--color-disabled-foreground)",
        },
        ink: {
          DEFAULT: "var(--color-ink)",
          soft: "var(--color-ink-soft)",
          foreground: "var(--color-ink-foreground)",
          muted: "var(--color-ink-muted)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "var(--color-success-foreground)",
          surface: "var(--color-success-surface)",
          border: "var(--color-success-border)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "var(--color-warning-foreground)",
          surface: "var(--color-warning-surface)",
          border: "var(--color-warning-border)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          foreground: "var(--color-error-foreground)",
          surface: "var(--color-error-surface)",
          border: "var(--color-error-border)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          foreground: "var(--color-info-foreground)",
          surface: "var(--color-info-surface)",
          border: "var(--color-info-border)",
        },
      },
      borderRadius: {
        card: "var(--radius-card)",
        control: "var(--radius-control)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        elevated: "var(--shadow-elevated)",
        focus: "var(--shadow-focus)",
      },
    },
  },
  plugins: [],
};

module.exports = config;
