/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        oat: {
          50: "#FDFAF3",
          100: "#F8F1E2",
          200: "#F0E4CB",
          300: "#E3D2AC",
          400: "#D2BB86",
          500: "#B89C63",
          600: "#94794A",
          700: "#6F593A",
          800: "#4A3B2A",
          900: "#2A2118",
          950: "#181208",
        },
        primary: {
          50: "#EEF1FF",
          100: "#DDE3FF",
          200: "#C1C9FF",
          300: "#9BA5FB",
          400: "#7B80F4",
          500: "#5E5EE8",
          600: "#4A44D7",
          700: "#3D36B4",
          800: "#322E91",
          900: "#2A2873",
          950: "#1B1844",
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          disabled: "var(--color-primary-disabled)",
        },
        secondary: {
          50: "#FFF5F0",
          100: "#FFE6DB",
          200: "#FFC8B1",
          300: "#FFA37C",
          400: "#FF7A48",
          500: "#FB5A25",
          600: "#E8421A",
          700: "#BF3315",
          800: "#962B16",
          900: "#7A2616",
          950: "#420F08",
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
          hover: "var(--color-secondary-hover)",
          active: "var(--color-secondary-active)",
          disabled: "var(--color-secondary-disabled)",
        },
        accent: {
          50: "#ECFDF5",
          100: "#D1FAE5",
          200: "#A7F3D0",
          300: "#6EE7B7",
          400: "#34D399",
          500: "#10B981",
          600: "#059669",
          700: "#047857",
          800: "#065F46",
          900: "#064E3B",
          950: "#022C22",
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
          hover: "var(--color-accent-hover)",
          active: "var(--color-accent-active)",
          disabled: "var(--color-accent-disabled)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          muted: "var(--color-surface-muted)",
          elevated: "var(--color-surface-elevated)",
          sunken: "var(--color-surface-sunken)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        disabled: {
          DEFAULT: "var(--color-disabled)",
          foreground: "var(--color-disabled-foreground)",
        },
        ink: {
          DEFAULT: "var(--color-ink)",
          soft: "var(--color-ink-soft)",
          foreground: "var(--color-ink-foreground)",
          muted: "var(--color-ink-muted)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "var(--color-success-foreground)",
          surface: "var(--color-success-surface)",
          border: "var(--color-success-border)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "var(--color-warning-foreground)",
          surface: "var(--color-warning-surface)",
          border: "var(--color-warning-border)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          foreground: "var(--color-error-foreground)",
          surface: "var(--color-error-surface)",
          border: "var(--color-error-border)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          foreground: "var(--color-info-foreground)",
          surface: "var(--color-info-surface)",
          border: "var(--color-info-border)",
        },
      },
      borderRadius: {
        card: "var(--radius-card)",
        control: "var(--radius-control)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        elevated: "var(--shadow-elevated)",
        focus: "var(--shadow-focus)",
      },
    },
  },
  plugins: [],
};

module.exports = config;
