/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist)", "system-ui", "sans-serif"],
        display: ["var(--font-fraunces)", "Georgia", "serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        oat: {
          50: "#F7F1E8",
          100: "#EFE7DA",
          200: "#E8DFD0",
          300: "#DDD2C0",
          400: "#C8B9A0",
          500: "#A8927D",
          600: "#8A735E",
          700: "#6A5645",
          800: "#463729",
          900: "#2A2018",
          950: "#18110B",
        },
        primary: {
          50: "#F4F0F7",
          100: "#ECE6F2",
          200: "#DDD2E3",
          300: "#C5B6CF",
          400: "#A899B8",
          500: "#8B7BA0",
          600: "#5E4E8A",
          700: "#514377",
          800: "#443866",
          900: "#382E54",
          950: "#1F1830",
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          disabled: "var(--color-primary-disabled)",
        },
        secondary: {
          50: "#FEF5EC",
          100: "#F7E3CD",
          200: "#F3D2B0",
          300: "#E9B387",
          400: "#DF9A64",
          500: "#D88A4A",
          600: "#B47237",
          700: "#8E592A",
          800: "#6C4321",
          900: "#4F3019",
          950: "#2C1A0C",
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
          hover: "var(--color-secondary-hover)",
          active: "var(--color-secondary-active)",
          disabled: "var(--color-secondary-disabled)",
        },
        accent: {
          50: "#F0F5ED",
          100: "#E1EAD9",
          200: "#C8D8C0",
          300: "#B5D49E",
          400: "#95B88A",
          500: "#6E9968",
          600: "#587B54",
          700: "#486343",
          800: "#354A32",
          900: "#243424",
          950: "#131C12",
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
          hover: "var(--color-accent-hover)",
          active: "var(--color-accent-active)",
          disabled: "var(--color-accent-disabled)",
        },
        danger: {
          50: "#FBEEEC",
          100: "#F4D7D4",
          200: "#ECBAB5",
          300: "#E09790",
          400: "#D2706A",
          500: "#C5453E",
          600: "#A53931",
          700: "#832C26",
          800: "#5F201C",
          900: "#3F1614",
          950: "#220A09",
        },
        info: {
          50: "#EEF3F8",
          100: "#DAE6EE",
          200: "#B9CEE0",
          300: "#8EB1CB",
          400: "#6995B4",
          500: "#4D7CA0",
          600: "#3E6582",
          700: "#305067",
          800: "#233B4C",
          900: "#182833",
          950: "#0C151C",
          DEFAULT: "var(--color-info)",
          foreground: "var(--color-info-foreground)",
          surface: "var(--color-info-surface)",
          border: "var(--color-info-border)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          muted: "var(--color-surface-muted)",
          elevated: "var(--color-surface-elevated)",
          sunken: "var(--color-surface-sunken)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        disabled: {
          DEFAULT: "var(--color-disabled)",
          foreground: "var(--color-disabled-foreground)",
        },
        ink: {
          DEFAULT: "var(--color-ink)",
          soft: "var(--color-ink-soft)",
          foreground: "var(--color-ink-foreground)",
          muted: "var(--color-ink-muted)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "var(--color-success-foreground)",
          surface: "var(--color-success-surface)",
          border: "var(--color-success-border)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "var(--color-warning-foreground)",
          surface: "var(--color-warning-surface)",
          border: "var(--color-warning-border)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          foreground: "var(--color-error-foreground)",
          surface: "var(--color-error-surface)",
          border: "var(--color-error-border)",
        },
      },
      borderRadius: {
        card: "var(--radius-card)",
        input: "var(--radius-input)",
        control: "var(--radius-control)",
        modal: "var(--radius-modal)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        elevated: "var(--shadow-elevated)",
        focus: "var(--shadow-focus)",
        pill: "var(--shadow-pill)",
      },
    },
  },
  plugins: [],
};

module.exports = config;
